import { IMediaItem } from '../types/index.js';

export const mockMediaContent: Omit<IMediaItem, 'createdAt' | 'updatedAt'>[] = [
  {
    title: 'The Future of AI in 2026',
    description: 'Exploring the latest trends and breakthroughs in artificial intelligence and machine learning.',
    type: 'article',
    url: 'https://example.com/ai-2026',
    thumbnail: 'https://via.placeholder.com/400x300?text=AI+Future',
    category: 'Technology',
    tags: ['ai', 'ml', 'technology', 'future'],
    views: 15420,
    likes: 1230,
    aiAnalysis: {
      sentiment: 'positive',
      topics: ['Artificial Intelligence', 'Machine Learning', 'Technology'],
      keywordScore: 0.87,
      engagement: 0.92,
      recommendations: [
        'Strong article for tech enthusiasts',
        'High engagement potential',
        'Covers trending AI topics',
      ],
    },
  },
  {
    title: 'Web Development Best Practices',
    description: 'A comprehensive guide to modern web development standards and practices.',
    type: 'article',
    url: 'https://example.com/webdev-best-practices',
    thumbnail: 'https://via.placeholder.com/400x300?text=Web+Dev',
    category: 'Technology',
    tags: ['webdev', 'javascript', 'react', 'typescript'],
    views: 8932,
    likes: 567,
    aiAnalysis: {
      sentiment: 'positive',
      topics: ['Web Development', 'Programming', 'JavaScript'],
      keywordScore: 0.79,
      engagement: 0.85,
      recommendations: ['Educational value high', 'Good for developers', 'Update with latest frameworks'],
    },
  },
  {
    title: 'Documentary: The Hidden World of Deep Sea',
    description: 'Journey beneath the waves to discover the mysteries of the deep ocean.',
    type: 'video',
    url: 'https://example.com/deep-sea-doc',
    thumbnail: 'https://via.placeholder.com/400x300?text=Deep+Sea',
    duration: 3600,
    category: 'Entertainment',
    tags: ['documentary', 'nature', 'ocean', 'adventure'],
    views: 45230,
    likes: 3890,
    aiAnalysis: {
      sentiment: 'positive',
      topics: ['Nature', 'Documentary', 'Ocean'],
      keywordScore: 0.83,
      engagement: 0.88,
      recommendations: ['Highly engaging content', 'Great visuals', 'Trending in nature category'],
    },
  },
  {
    title: 'Quantum Computing Explained',
    description: 'Understanding the basics of quantum computing and its potential applications.',
    type: 'article',
    url: 'https://example.com/quantum-computing',
    thumbnail: 'https://via.placeholder.com/400x300?text=Quantum',
    category: 'Technology',
    tags: ['quantum', 'computing', 'physics', 'future-tech'],
    views: 12567,
    likes: 987,
    aiAnalysis: {
      sentiment: 'neutral',
      topics: ['Quantum Computing', 'Physics', 'Technology'],
      keywordScore: 0.75,
      engagement: 0.80,
      recommendations: ['Technical content for specialists', 'Consider simpler explanation', 'Add more visuals'],
    },
  },
  {
    title: 'Music Production Tips for Beginners',
    description: 'Essential tips and tricks for aspiring music producers getting started with DAWs.',
    type: 'article',
    url: 'https://example.com/music-production-tips',
    thumbnail: 'https://via.placeholder.com/400x300?text=Music+Production',
    category: 'Music',
    tags: ['music', 'production', 'daw', 'beginners'],
    views: 6234,
    likes: 432,
    aiAnalysis: {
      sentiment: 'positive',
      topics: ['Music Production', 'Audio Engineering', 'Tutorials'],
      keywordScore: 0.81,
      engagement: 0.82,
      recommendations: ['Great for beginners', 'Practical tips', 'Consider adding video tutorials'],
    },
  },
  {
    title: 'Health Benefits of Regular Exercise',
    description: 'Scientific insights into how regular physical activity improves overall health and wellbeing.',
    type: 'article',
    url: 'https://example.com/exercise-benefits',
    thumbnail: 'https://via.placeholder.com/400x300?text=Health+Fitness',
    category: 'Health',
    tags: ['health', 'fitness', 'exercise', 'wellness'],
    views: 20145,
    likes: 1876,
    aiAnalysis: {
      sentiment: 'positive',
      topics: ['Health', 'Fitness', 'Science'],
      keywordScore: 0.86,
      engagement: 0.89,
      recommendations: ['High health audience interest', 'Scientific backing appreciated', 'Add exercise videos'],
    },
  },
];
